set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

set(LLVM_BIN "C:/Program Files/LLVM/bin")

set(CMAKE_C_COMPILER    "${LLVM_BIN}/clang.exe")
set(CMAKE_CXX_COMPILER  "${LLVM_BIN}/clang++.exe")
set(CMAKE_ASM_COMPILER  "${LLVM_BIN}/clang.exe")
set(CMAKE_LINKER        "${LLVM_BIN}/ld.lld.exe")

set(BARE_METAL_FLAGS "--target=x86_64-unknown-none-elf -ffreestanding -nostdlib")

set(CMAKE_C_FLAGS   "${BARE_METAL_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS "${BARE_METAL_FLAGS}" CACHE STRING "" FORCE)

set(CMAKE_C_LINK_EXECUTABLE "\"${CMAKE_LINKER}\" <LINK_FLAGS> <OBJECTS> -o <TARGET>" CACHE STRING "" FORCE)
set(CMAKE_ASM_LINK_EXECUTABLE "\"${CMAKE_LINKER}\" <LINK_FLAGS> <OBJECTS> -o <TARGET>" CACHE STRING "" FORCE)
